- Bugfix:  New file, "Timer.h", not added to the source package. - Added status messages to the package install/remove scriptlets.   Not only tracks what's going on for users, but aids debugging the   packages themselves.
git-svn-id: file:///home/candide/src/0_Local_SVN_Repos/msnek4kDriverDaemon/trunk@2171 92e5ae4a-8afd-0310-8b33-eaebc6dd6768

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -19,6 +19,7 @@ set -e
 
 case "$1" in
     remove|upgrade|deconfigure)
+        echo "Stopping the previous version of 'msnek4k_driverd' ..." >&2
         if [ -x /usr/bin/pkill ]; then
             /usr/bin/pkill msnek4k_driverd
         else
@@ -31,6 +32,10 @@ case "$1" in
     ;;
 
     failed-upgrade)
+        echo "Upgrade failed.  'msnek4k_driverd' is no longer running." >&2
+        echo "Run the following as root to restart it:" >&2
+        echo "        . ${XSESSIONDIR}/90x11-msnek4k_driverd" >&2
+        echo "" >&2
     ;;
 
     *)
